services:
  tirex:
    # tirex + mapnik (renderer)
    image: osm-tileserver-tirex:1.0
    build: ./src_tirex/

    volumes:
      - ./volumes/shared/transfer:/transfer
      - ./volumes/shared/var/run/renderd:/var/run/renderd
      - /media/hdd/openstreetmap-tilecache:/var/lib/mod_tile

    hostname: osmtileserver-tirex

    external_links:
      - osm-tileserver-db:osm-tileserver-db

    command: run

    networks:
      - proxy
      - tile-postgis-network

  web:
    # apache + mod_tile (web frontend)
    image: osm-tileserver-web:1.0
    build: ./src_apache/

    volumes:
      - ./volumes/web/etc/apache2/sites-available/apache.conf:/etc/apache2/sites-available/000-default.conf
      - ./volumes/web/etc/apache2/conf-available/mod_tile.conf:/etc/apache2/conf-available/mod_tile.conf
      - ./volumes/web/usr/local/etc/renderd.conf:/usr/local/etc/renderd.conf
      - ./volumes/web/log/apache:/var/log/apache
      - ./volumes/web/www/index.html:/var/www/html/index.html

      - ./volumes/shared/var/run/renderd:/var/run/renderd
      - /media/hdd/openstreetmap-tilecache:/var/lib/mod_tile

    hostname: osmtileserver

    external_links:
      - osm-tileserver-db:osm-tileserver-db

    command: run

    ports:
      - 80:80 

    networks:
      - proxy
      - tile-postgis-network

volumes:
  openstreetmap-tilecache:
    external: true

networks:
  proxy:
    external: true
  tile-postgis-network:
    external: true    
