version: '3'
services:
  osmtileserver:
    # tileserver (apache/mod-tile/tirex/mapnik)
    image: osm-tileserver:1.1
    build: ./src/

    volumes:
      - ./volumes/transfer:/transfer
      - ./volumes/etc/apache2/sites-available/apache.conf:/etc/apache2/sites-available/000-default.conf
      - ./volumes/log/appache:/var/log/appache
      - openstreetmap-tilecache:/var/lib/mod_tile

    hostname: osmtileserver

    external_links:
      - osm-tileserver-db:osm-tileserver-db

    command: run

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.osmtileserver.entrypoints=http"
      - "traefik.http.routers.osmtileserver.rule=Host(`t2.openseamap.org`)"
      - "traefik.http.middlewares.osmtileserver-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.osmtileserver.middlewares=osmtileserver-https-redirect"
      - "traefik.http.routers.osmtileserver-secure.entrypoints=https"
      - "traefik.http.routers.osmtileserver-secure.rule=Host(`t2.openseamap.org`)"
      - "traefik.http.routers.osmtileserver-secure.tls=true" 
      - "traefik.http.routers.osmtileserver-secure.tls.certresolver=http" 
      - "traefik.http.routers.osmtileserver-secure.service=osmtileserver" 
      - "traefik.http.services.osmtileserver.loadbalancer.server.port=80" 
      - "traefik.docker.network=proxy" 
      - "traefik.http.routers.osmtileserver.middlewares=cors-headers@docker" 
      - "traefik.http.middlewares.cors-headers.headers.accessControlAllowOriginList=*" 
      - "traefik.http.middlewares.cors-headers.headers.accessControlAllowHeaders=Origin, X-Requested-With, Content-Type, Accept, Authorization" 
      - "traefik.http.middlewares.cors-headers.headers.accessControlAllowMethods=GET, POST, PUT, DELETE, OPTIONS"
    
    networks:
      - proxy

volumes:
  openstreetmap-tilecache:
    external: true

networks:
  proxy:
    external: true